Repository evenyag/greptimedb, pull requests merged in 2024-02, with the labels that each got.

#6 feat: skeleton for data builder
  src/mito2/src/memtable/merge_tree.rs
  src/mito2/src/memtable/merge_tree/data.rs
Labels: Size: M

#7 feat: index reader
  src/mito2/src/memtable/merge_tree/index.rs
Labels: Size: M

#8 feat: data encoder
  src/mito2/src/error.rs
  src/mito2/src/memtable/merge_tree/data.rs
  src/mito2/src/test_util/memtable_util.rs
Labels: Size: M

#10 feat: Add a new method fork to create a mutable memtable
  src/mito2/src/flush.rs
  src/mito2/src/memtable.rs
  src/mito2/src/memtable/merge_tree.rs
  src/mito2/src/memtable/time_series.rs
  src/mito2/src/memtable/version.rs
  src/mito2/src/region/version.rs
  src/mito2/src/test_util/memtable_util.rs
  src/mito2/src/worker/handle_flush.rs
Labels: Size: S

#11 feat: Add a sorted index to the mutable index shard
  Cargo.lock
  src/mito2/Cargo.toml
  src/mito2/src/memtable/merge_tree.rs
  src/mito2/src/memtable/merge_tree/index.rs
  src/mito2/src/test_util/version_util.rs
Labels: Size: M

#12 feat: Implement freeze and fork for index
  src/mito2/src/memtable.rs
  src/mito2/src/memtable/merge_tree.rs
  src/mito2/src/memtable/merge_tree/data.rs
  src/mito2/src/memtable/merge_tree/index.rs
  src/mito2/src/memtable/merge_tree/tree.rs
  src/mito2/src/test_util/version_util.rs
Labels: Size: M

#13 feat: read data parts API
  src/mito2/src/memtable/merge_tree/data.rs
Labels: Size: M

#15 feat: single data part iter
  src/mito2/src/error.rs
  src/mito2/src/memtable/merge_tree/data.rs
Labels: Size: M

#14 feat: Iterator for single shard in the tree
  src/mito2/src/memtable/merge_tree/data.rs
  src/mito2/src/memtable/merge_tree/index.rs
  src/mito2/src/memtable/merge_tree/tree.rs
Labels: Size: M

#17 feat: finish read/write for single shard
  src/mito2/src/memtable.rs
  src/mito2/src/memtable/merge_tree.rs
  src/mito2/src/memtable/merge_tree/data.rs
  src/mito2/src/memtable/merge_tree/index.rs
  src/mito2/src/memtable/merge_tree/tree.rs
Labels: Size: L

#18 fix: fixes issues related to the single shard merge tree
  src/mito2/src/config.rs
  src/mito2/src/flush.rs
  src/mito2/src/memtable.rs
  src/mito2/src/memtable/merge_tree.rs
  src/mito2/src/memtable/merge_tree/data.rs
  src/mito2/src/memtable/merge_tree/index.rs
  src/mito2/src/memtable/merge_tree/mutable.rs
  src/mito2/src/memtable/merge_tree/tree.rs
  src/mito2/src/worker.rs
Labels: Size: M
